# Uncomment this if you're getting socket timeout errors when running yarn install, but
# you shouldn't need to commit it with this uncommented; once the yarn.lock file is
# generated, it should be fine to comment this out again.
#httpTimeout: 600000

defaultSemverRangePrefix: ""
compressionLevel: mixed
enableGlobalCache: false

logFilters:
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://artifactory.build.ue1.snooguts.net/artifactory/api/npm/reddit-npm-prod/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
