compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: true

logFilters:
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://artifactory.build.ue1.snooguts.net/artifactory/api/npm/reddit-npm-prod/"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
