export type {
  // string literal types
  T1 as T1ID,
  T2 as T2ID,
  T3 as T3ID,
  T4 as T4ID,
  T5 as T5ID,
  T6 as T6ID,
  Tid as TID,
} from '@devvit/shared-types/tid.js';
export {
  // assertion functions
  assertT1 as assertT1ID,
  assertT2 as assertT2ID,
  assertT3 as assertT3ID,
  assertT4 as assertT4ID,
  assertT5 as assertT5ID,
  assertT6 as assertT6ID,
  // factory functions
  T1 as asT1ID,
  T2 as asT2ID,
  T3 as asT3ID,
  T4 as asT4ID,
  T5 as asT5ID,
  T6 as asT6ID,
  asTid as asTID,
  isT2 as isAccountId,
  isT6 as isAwardId,
  // convenience functions
  isT1 as isCommentId,
  isT3 as isLinkId,
  isT4 as isMessageId,
  isT5 as isSubredditId,
  // type guards
  isT1 as isT1ID,
  isT2 as isT2ID,
  isT3 as isT3ID,
  isT4 as isT4ID,
  isT5 as isT5ID,
  isT6 as isT6ID,
  T_PREFIX,
} from '@devvit/shared-types/tid.js';
