export const demoNflGame12: any = {
  id: 'demo-nfl-game-12',
  status: 'inprogress',
  scheduled: '2024-01-07T01:15:00+00:00',
  entry_mode: 'LDE',
  clock: '00:08',
  quarter: 4,
  sr_id: 'sr:match:41209665',
  game_type: 'regular',
  conference_game: true,
  weather: {
    condition: 'Mist',
    humidity: 92,
    temp: 35,
    wind: {
      speed: 2,
      direction: 'N',
    },
  },
  coin_toss: [
    {
      home: {
        outcome: 'lost',
        decision: 'receive',
      },
      away: {
        outcome: 'won',
        decision: 'defer',
      },
      quarter: 1,
    },
    {
      home: {
        outcome: 'lost',
        decision: 'kick',
      },
      away: {
        outcome: 'won',
        decision: 'receive',
      },
      quarter: 3,
    },
  ],
  summary: {
    season: {
      id: 'a538d200-e916-4272-aa07-b486094a1668',
      year: 2023,
      type: 'REG',
      name: 'REG',
    },
    week: {
      id: '7723bce4-a683-4152-b95d-42bce6e98d9c',
      sequence: 18,
      title: '18',
    },
    venue: {
      id: '6ed18563-53e0-46c2-a91d-12d73a16456d',
      name: 'Lucas Oil Stadium',
      city: 'Indianapolis',
      state: 'IN',
      country: 'USA',
      zip: '46225',
      address: '500 South Capitol Avenue',
      capacity: 67000,
      surface: 'artificial',
      roof_type: 'retractable_dome',
      sr_id: 'sr:venue:8185',
      location: {
        lat: '39.760008',
        lng: '-86.163906',
      },
    },
    home: {
      id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
      name: 'Colts',
      market: 'Indianapolis',
      alias: 'IND',
      sr_id: 'sr:competitor:4421',
      used_timeouts: 3,
      remaining_timeouts: 0,
      points: 19,
      used_challenges: 1,
      remaining_challenges: 1,
    },
    away: {
      id: '82d2d380-3834-4938-835f-aec541e5ece7',
      name: 'Texans',
      market: 'Houston',
      alias: 'HOU',
      sr_id: 'sr:competitor:4324',
      used_timeouts: 1,
      remaining_timeouts: 2,
      points: 23,
      used_challenges: 0,
      remaining_challenges: 2,
    },
  },
  situation: {
    clock: '00:01',
    down: 0,
    yfd: 0,
    possession: {
      id: '82d2d380-3834-4938-835f-aec541e5ece7',
      name: 'Texans',
      market: 'Houston',
      alias: 'HOU',
      sr_id: 'sr:competitor:4324',
    },
    location: {
      id: '82d2d380-3834-4938-835f-aec541e5ece7',
      name: 'Texans',
      market: 'Houston',
      alias: 'HOU',
      sr_id: 'sr:competitor:4324',
      yardline: 20,
    },
  },
  last_event: {
    type: 'play',
    id: '9b47ec70-ad13-11ee-b18e-11f7316c1a9e',
    sequence: 1704601131224,
    clock: '00:08',
    home_points: 19,
    away_points: 23,
    play_type: 'rush',
    scoring_play: true,
    wall_clock: '2024-01-07T04:18:05+00:00',
    description:
      'C.Johnston rushed up the middle to HOU End Zone for -23 yards. Pushed out of bounds by E.Speed at HOU End Zone. SAFETY.',
    scoring_description:
      'C.Johnston rushed up the middle to HOU End Zone for -23 yards. Pushed out of bounds by E.Speed at HOU End Zone. SAFETY.',
    fake_punt: false,
    fake_field_goal: false,
    screen_pass: false,
    play_action: false,
    run_pass_option: false,
    created_at: '2024-01-07T04:18:51+00:00',
    updated_at: '2024-01-07T04:19:17+00:00',
    start_situation: {
      clock: '00:08',
      down: 4,
      yfd: 2,
      possession: {
        id: '82d2d380-3834-4938-835f-aec541e5ece7',
        name: 'Texans',
        market: 'Houston',
        alias: 'HOU',
        sr_id: 'sr:competitor:4324',
      },
      location: {
        id: '82d2d380-3834-4938-835f-aec541e5ece7',
        name: 'Texans',
        market: 'Houston',
        alias: 'HOU',
        sr_id: 'sr:competitor:4324',
        yardline: 23,
      },
    },
    end_situation: {
      clock: '00:01',
      down: 0,
      yfd: 0,
      possession: {
        id: '82d2d380-3834-4938-835f-aec541e5ece7',
        name: 'Texans',
        market: 'Houston',
        alias: 'HOU',
        sr_id: 'sr:competitor:4324',
      },
      location: {
        id: '82d2d380-3834-4938-835f-aec541e5ece7',
        name: 'Texans',
        market: 'Houston',
        alias: 'HOU',
        sr_id: 'sr:competitor:4324',
        yardline: 20,
      },
    },
    score: {
      sequence: 13,
      clock: '00:01',
      points: 2,
      home_points: 19,
      away_points: 23,
    },
    statistics: [
      {
        stat_type: 'rush',
        attempt: 1,
        yards: -23,
        firstdown: 0,
        safety: 1,
        inside_20: 0,
        goaltogo: 0,
        tlost: 1,
        tlost_yards: -23,
        broken_tackles: 0,
        kneel_down: 0,
        scramble: 0,
        player: {
          id: 'd2f6de91-089a-4845-9b90-bfbc00487444',
          name: 'Cameron Johnston',
          jersey: '11',
          position: 'P',
          sr_id: 'sr:player:1130391',
        },
        team: {
          id: '82d2d380-3834-4938-835f-aec541e5ece7',
          name: 'Texans',
          market: 'Houston',
          alias: 'HOU',
          sr_id: 'sr:competitor:4324',
        },
      },
      {
        stat_type: 'defense',
        safety: 1,
        category: 'defense',
        def_target: 0,
        def_comp: 0,
        blitz: 0,
        hurry: 0,
        knockdown: 0,
        batted_pass: 0,
        team: {
          id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
          name: 'Colts',
          market: 'Indianapolis',
          alias: 'IND',
          sr_id: 'sr:competitor:4421',
        },
      },
      {
        stat_type: 'defense',
        tackle: 1,
        tlost: 1,
        tlost_yards: 23,
        category: 'defense',
        def_target: 0,
        def_comp: 0,
        blitz: 0,
        hurry: 0,
        knockdown: 0,
        batted_pass: 0,
        player: {
          id: 'e653effc-2bdc-4bfe-bf3d-272e783ae4c4',
          name: 'E.J. Speed',
          jersey: '45',
          position: 'LB',
          sr_id: 'sr:player:1833904',
        },
        team: {
          id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
          name: 'Colts',
          market: 'Indianapolis',
          alias: 'IND',
          sr_id: 'sr:competitor:4421',
        },
      },
    ],
    details: [
      {
        category: 'rush',
        description: 'C.Johnston rushed up the middle to HOU End Zone for -23 yards.',
        sequence: 0,
        direction: 'up the middle',
        yards: -23,
        result: 'pushed out of bounds',
        start_location: {
          alias: 'HOU',
          yardline: 23,
        },
        end_location: {
          alias: 'HOU',
          yardline: 0,
        },
        players: [
          {
            id: 'd2f6de91-089a-4845-9b90-bfbc00487444',
            name: 'Cameron Johnston',
            jersey: '11',
            position: 'P',
            sr_id: 'sr:player:1130391',
            role: 'rush',
          },
        ],
      },
      {
        category: 'pushed_out_of_bounds',
        description: 'Pushed out of bounds by E.Speed at HOU End Zone.',
        sequence: 1,
        start_location: {
          alias: 'HOU',
          yardline: 0,
        },
        end_location: {
          alias: 'HOU',
          yardline: 0,
        },
        players: [
          {
            id: 'e653effc-2bdc-4bfe-bf3d-272e783ae4c4',
            name: 'E.J. Speed',
            jersey: '45',
            position: 'LB',
            sr_id: 'sr:player:1833904',
            role: 'tackle',
          },
        ],
      },
      {
        category: 'safety',
        description: 'SAFETY.',
        sequence: 2,
        start_location: {
          alias: 'HOU',
          yardline: 0,
        },
        end_location: {
          alias: 'HOU',
          yardline: 0,
        },
        players: [],
      },
    ],
  },
  scoring: [
    {
      period_type: 'quarter',
      id: '3783d9e7-4fb1-44ed-823b-d98f3f1642d3',
      number: 1,
      sequence: 1,
      home_points: 3,
      away_points: 7,
    },
    {
      period_type: 'quarter',
      id: '2b6d464b-9d52-409f-a8b3-d10f4c81fc33',
      number: 2,
      sequence: 2,
      home_points: 3,
      away_points: 7,
    },
    {
      period_type: 'quarter',
      id: '31b467ed-0f08-4499-9f26-bab75a930809',
      number: 3,
      sequence: 3,
      home_points: 8,
      away_points: 3,
    },
    {
      period_type: 'quarter',
      id: '3edcce8e-baa0-4fc5-8900-061bedcb5ee4',
      number: 4,
      sequence: 4,
      home_points: 5,
      away_points: 6,
    },
  ],
};
