import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction to Devvit',
      collapsible: false,
      items: [
        'introduction/introduction',
        'introduction/intro-games',
        'introduction/intro-mod-tools',
      ],
    },
    {
      type: 'category',
      label: 'Build Your App',
      collapsible: false,
      items: [
        'quickstart/quickstart',
        'quickstart/quickstart-mod-tool',
        {
          type: 'category',
          label: 'Capabilities',
          collapsible: false,
          items: [
            'capabilities/devvit-web/devvit_web_overview',
            'capabilities/devvit-web/devvit_web_configuration',
            {
              type: 'category',
              label: 'Client',
              items: [
                'capabilities/client/overview',
                'capabilities/client/navigation',
                'capabilities/client/forms',
                'capabilities/client/toasts',
                'capabilities/client/menu-actions',
              ],
            },
            {
              type: 'category',
              label: 'Server',
              items: [
                'capabilities/server/overview',
                'capabilities/server/redis',
                'capabilities/server/userActions',
                'capabilities/server/post-data',
                'capabilities/server/splash-screen',
                'capabilities/server/text_fallback',
                'capabilities/server/scheduler',
                'capabilities/server/triggers',
                'capabilities/server/media-uploads',
                'capabilities/server/settings-and-secrets',
                'capabilities/server/http-fetch',
                {
                  type: 'category',
                  label: 'Reddit API',
                  items: [
                    {
                      type: 'doc',
                      label: 'Overview',
                      id: 'capabilities/server/reddit-api',
                    },
                    {
                      type: 'category',
                      label: 'API Reference',
                      items: [
                        {
                          type: 'doc',
                          label: 'Reddit API Client',
                          id: 'api/redditapi/RedditAPIClient/classes/RedditAPIClient',
                        },
                        {
                          type: 'category',
                          label: 'Classes',
                          items: [
                            {
                              type: 'autogenerated',
                              dirName: 'api/redditapi/models/classes',
                            },
                          ],
                        },
                        {
                          type: 'category',
                          label: 'Interfaces',
                          items: [
                            {
                              type: 'autogenerated',
                              dirName: 'api/redditapi/models/interfaces',
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Realtime',
              items: [
                'capabilities/realtime/overview',
                'capabilities/realtime/realtime_in_devvit_blocks',
              ],
            },
            {
              type: 'category',
              label: 'Devvit Blocks',
              items: [
                'capabilities/blocks/overview',
                'capabilities/blocks/dimensions',
                'capabilities/blocks/working_with_usestate',
                'capabilities/blocks/working_with_useinterval',
                'capabilities/blocks/working_with_useasync',
                'capabilities/blocks/app_image_assets',
                'capabilities/blocks/cache',
                {
                  type: 'category',
                  label: 'Reference',
                  items: [
                    'blocks/stacks',
                    'blocks/text',
                    'blocks/icon',
                    'blocks/button',
                    'blocks/image',
                    'blocks/spacer',
                    'blocks/colors',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      label: 'Launch Your App',
      id: 'guides/launch/launch-guide',
    },
    {
      type: 'category',
      label: 'Earn Money',
      collapsible: false,
      items: [
        'earn-money/reddit_developer_funds',
        {
          type: 'category',
          label: 'Payments',
          items: [
            'earn-money/payments/payments_overview',
            'earn-money/payments/payments_add',
            'earn-money/payments/payments_test',
            'earn-money/payments/payments_publish',
            'earn-money/payments/payments_manage',
            'earn-money/payments/support_this_app',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsible: false,
      items: ['examples/app-showcase', 'examples/template-library'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Development Tools',
          items: [
            'guides/tools/devvit_cli',
            'guides/tools/logs',
            'guides/tools/playtest',
            'guides/tools/ui_simulator',
          ],
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: ['guides/best-practices/community_games', 'guides/best-practices/mod_resources'],
        },
        {
          type: 'category',
          label: 'Migration Guides',
          items: [
            'guides/migrate/devvit-singleton',
            'guides/migrate/devvit-web-experimental',
            'guides/migrate/inline-web-view',
          ],
        },
      ],
    },
    {
      type: 'doc',
      label: 'Changelog',
      id: 'changelog',
    },
    {
      type: 'doc',
      label: 'Devvit Rules',
      id: 'devvit_rules',
    },
    {
      type: 'link',
      label: 'Discord',
      href: 'https://discord.gg/Cd43ExtEFS',
      className: 'sidebar-icon-link discord-link',
    },
    {
      type: 'link',
      label: 'r/Devvit',
      href: 'https://www.reddit.com/r/devvit/',
      className: 'sidebar-icon-link subreddit-link',
    },
  ],
};

export default sidebars;
