export const demoNflGame07: unknown = {
  id: 'demo-nfl-game-07',
  status: 'inprogress',
  scheduled: '2024-01-07T01:15:00+00:00',
  entry_mode: 'LDE',
  clock: '10:33',
  quarter: 3,
  sr_id: 'sr:match:41209665',
  game_type: 'regular',
  conference_game: true,
  weather: {
    condition: 'Mist',
    humidity: 92,
    temp: 35,
    wind: {
      speed: 2,
      direction: 'N',
    },
  },
  coin_toss: [
    {
      home: {
        outcome: 'lost',
        decision: 'receive',
      },
      away: {
        outcome: 'won',
        decision: 'defer',
      },
      quarter: 1,
    },
    {
      home: {
        outcome: 'lost',
        decision: 'kick',
      },
      away: {
        outcome: 'won',
        decision: 'receive',
      },
      quarter: 3,
    },
  ],
  summary: {
    season: {
      id: 'a538d200-e916-4272-aa07-b486094a1668',
      year: 2023,
      type: 'REG',
      name: 'REG',
    },
    week: {
      id: '7723bce4-a683-4152-b95d-42bce6e98d9c',
      sequence: 18,
      title: '18',
    },
    venue: {
      id: '6ed18563-53e0-46c2-a91d-12d73a16456d',
      name: 'Lucas Oil Stadium',
      city: 'Indianapolis',
      state: 'IN',
      country: 'USA',
      zip: '46225',
      address: '500 South Capitol Avenue',
      capacity: 67000,
      surface: 'artificial',
      roof_type: 'retractable_dome',
      sr_id: 'sr:venue:8185',
      location: {
        lat: '39.760008',
        lng: '-86.163906',
      },
    },
    home: {
      id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
      name: 'Colts',
      market: 'Indianapolis',
      alias: 'IND',
      sr_id: 'sr:competitor:4421',
      used_timeouts: 0,
      remaining_timeouts: 3,
      points: 6,
      used_challenges: 0,
      remaining_challenges: 2,
    },
    away: {
      id: '82d2d380-3834-4938-835f-aec541e5ece7',
      name: 'Texans',
      market: 'Houston',
      alias: 'HOU',
      sr_id: 'sr:competitor:4324',
      used_timeouts: 0,
      remaining_timeouts: 3,
      points: 14,
      used_challenges: 0,
      remaining_challenges: 2,
    },
  },
  situation: {
    clock: '10:21',
    down: 1,
    yfd: 10,
    possession: {
      id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
      name: 'Colts',
      market: 'Indianapolis',
      alias: 'IND',
      sr_id: 'sr:competitor:4421',
    },
    location: {
      id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
      name: 'Colts',
      market: 'Indianapolis',
      alias: 'IND',
      sr_id: 'sr:competitor:4421',
      yardline: 50,
    },
  },
  last_event: {
    type: 'play',
    id: '2b04f480-ad09-11ee-b18e-11f7316c1a9e',
    sequence: 1704596568066,
    clock: '10:33',
    home_points: 6,
    away_points: 14,
    play_type: 'pass',
    wall_clock: '2024-01-07T03:02:35+00:00',
    description:
      'G.Minshew pass complete to IND 28. Catch made by K.Granson at IND 28. Gain of 22 yards. Tackled by HOU at IND 50.',
    fake_punt: false,
    fake_field_goal: false,
    screen_pass: false,
    play_action: false,
    run_pass_option: false,
    created_at: '2024-01-07T03:02:48+00:00',
    updated_at: '2024-01-07T03:02:50+00:00',
    start_situation: {
      clock: '10:33',
      down: 2,
      yfd: 6,
      possession: {
        id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
        name: 'Colts',
        market: 'Indianapolis',
        alias: 'IND',
        sr_id: 'sr:competitor:4421',
      },
      location: {
        id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
        name: 'Colts',
        market: 'Indianapolis',
        alias: 'IND',
        sr_id: 'sr:competitor:4421',
        yardline: 28,
      },
    },
    end_situation: {
      clock: '10:21',
      down: 1,
      yfd: 10,
      possession: {
        id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
        name: 'Colts',
        market: 'Indianapolis',
        alias: 'IND',
        sr_id: 'sr:competitor:4421',
      },
      location: {
        id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
        name: 'Colts',
        market: 'Indianapolis',
        alias: 'IND',
        sr_id: 'sr:competitor:4421',
        yardline: 50,
      },
    },
    statistics: [
      {
        stat_type: 'pass',
        attempt: 1,
        complete: 1,
        yards: 22,
        att_yards: 0,
        firstdown: 1,
        inside_20: 0,
        goaltogo: 0,
        blitz: 0,
        hurry: 0,
        knockdown: 0,
        on_target_throw: 0,
        batted_pass: 0,
        player: {
          id: 'dabb52c0-455b-48fe-996b-abf758120623',
          name: 'Gardner Minshew',
          jersey: '10',
          position: 'QB',
          sr_id: 'sr:player:1222634',
        },
        team: {
          id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
          name: 'Colts',
          market: 'Indianapolis',
          alias: 'IND',
          sr_id: 'sr:competitor:4421',
        },
      },
      {
        stat_type: 'receive',
        firstdown: 1,
        target: 1,
        reception: 1,
        yards: 22,
        yards_after_catch: 22,
        inside_20: 0,
        goaltogo: 0,
        catchable: 0,
        player: {
          id: 'bcc0167c-05fd-4b23-981e-60b8784ceb33',
          name: 'Kylen Granson',
          jersey: '83',
          position: 'TE',
          sr_id: 'sr:player:2198142',
        },
        team: {
          id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
          name: 'Colts',
          market: 'Indianapolis',
          alias: 'IND',
          sr_id: 'sr:competitor:4421',
        },
      },
      {
        stat_type: 'defense',
        tackle: 1,
        category: 'defense',
        def_target: 0,
        def_comp: 0,
        blitz: 0,
        hurry: 0,
        knockdown: 0,
        batted_pass: 0,
        team: {
          id: '82d2d380-3834-4938-835f-aec541e5ece7',
          name: 'Texans',
          market: 'Houston',
          alias: 'HOU',
          sr_id: 'sr:competitor:4324',
        },
      },
      {
        stat_type: 'first_down',
        category: 'pass',
        team: {
          id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
          name: 'Colts',
          market: 'Indianapolis',
          alias: 'IND',
          sr_id: 'sr:competitor:4421',
        },
      },
    ],
    details: [
      {
        category: 'pass_completion',
        description: 'G.Minshew pass complete to IND 28.',
        sequence: 0,
        yards: 22,
        start_location: {
          alias: 'IND',
          yardline: 28,
        },
        end_location: {
          alias: 'IND',
          yardline: 28,
        },
        players: [
          {
            id: 'dabb52c0-455b-48fe-996b-abf758120623',
            name: 'Gardner Minshew',
            jersey: '10',
            position: 'QB',
            sr_id: 'sr:player:1222634',
            role: 'pass',
          },
        ],
      },
      {
        category: 'pass_reception',
        description: 'Catch made by K.Granson at IND 28. Gain of 22 yards.',
        sequence: 1,
        yards: 22,
        result: 'tackled',
        start_location: {
          alias: 'IND',
          yardline: 28,
        },
        end_location: {
          alias: 'IND',
          yardline: 50,
        },
        players: [
          {
            id: 'bcc0167c-05fd-4b23-981e-60b8784ceb33',
            name: 'Kylen Granson',
            jersey: '83',
            position: 'TE',
            sr_id: 'sr:player:2198142',
            role: 'catch',
          },
        ],
      },
      {
        category: 'tackle',
        description: 'Tackled by HOU at IND 50.',
        sequence: 2,
        start_location: {
          alias: 'IND',
          yardline: 50,
        },
        end_location: {
          alias: 'IND',
          yardline: 50,
        },
        players: [],
      },
      {
        category: 'first_down',
        sequence: 3,
        result: 'pass',
        start_location: {
          alias: 'IND',
          yardline: 50,
        },
        end_location: {
          alias: 'IND',
          yardline: 50,
        },
        players: [],
      },
    ],
  },
  scoring: [
    {
      period_type: 'quarter',
      id: '3783d9e7-4fb1-44ed-823b-d98f3f1642d3',
      number: 1,
      sequence: 1,
      home_points: 3,
      away_points: 7,
    },
    {
      period_type: 'quarter',
      id: '2b6d464b-9d52-409f-a8b3-d10f4c81fc33',
      number: 2,
      sequence: 2,
      home_points: 3,
      away_points: 7,
    },
    {
      period_type: 'quarter',
      id: '31b467ed-0f08-4499-9f26-bab75a930809',
      number: 3,
      sequence: 3,
      home_points: 0,
      away_points: 0,
    },
  ],
};
