export const demoNflGame09: any = {
  id: 'demo-nfl-game-09',
  status: 'inprogress',
  scheduled: '2024-01-07T01:15:00+00:00',
  entry_mode: 'LDE',
  clock: '9:43',
  quarter: 4,
  sr_id: 'sr:match:41209665',
  game_type: 'regular',
  conference_game: true,
  weather: {
    condition: 'Mist',
    humidity: 92,
    temp: 35,
    wind: {
      speed: 2,
      direction: 'N',
    },
  },
  coin_toss: [
    {
      home: {
        outcome: 'lost',
        decision: 'receive',
      },
      away: {
        outcome: 'won',
        decision: 'defer',
      },
      quarter: 1,
    },
    {
      home: {
        outcome: 'lost',
        decision: 'kick',
      },
      away: {
        outcome: 'won',
        decision: 'receive',
      },
      quarter: 3,
    },
  ],
  summary: {
    season: {
      id: 'a538d200-e916-4272-aa07-b486094a1668',
      year: 2023,
      type: 'REG',
      name: 'REG',
    },
    week: {
      id: '7723bce4-a683-4152-b95d-42bce6e98d9c',
      sequence: 18,
      title: '18',
    },
    venue: {
      id: '6ed18563-53e0-46c2-a91d-12d73a16456d',
      name: 'Lucas Oil Stadium',
      city: 'Indianapolis',
      state: 'IN',
      country: 'USA',
      zip: '46225',
      address: '500 South Capitol Avenue',
      capacity: 67000,
      surface: 'artificial',
      roof_type: 'retractable_dome',
      sr_id: 'sr:venue:8185',
      location: {
        lat: '39.760008',
        lng: '-86.163906',
      },
    },
    home: {
      id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
      name: 'Colts',
      market: 'Indianapolis',
      alias: 'IND',
      sr_id: 'sr:competitor:4421',
      used_timeouts: 0,
      remaining_timeouts: 3,
      points: 17,
      used_challenges: 1,
      remaining_challenges: 1,
    },
    away: {
      id: '82d2d380-3834-4938-835f-aec541e5ece7',
      name: 'Texans',
      market: 'Houston',
      alias: 'HOU',
      sr_id: 'sr:competitor:4324',
      used_timeouts: 0,
      remaining_timeouts: 3,
      points: 17,
      used_challenges: 0,
      remaining_challenges: 2,
    },
  },
  situation: {
    clock: '9:43',
    down: 1,
    yfd: 10,
    possession: {
      id: '82d2d380-3834-4938-835f-aec541e5ece7',
      name: 'Texans',
      market: 'Houston',
      alias: 'HOU',
      sr_id: 'sr:competitor:4324',
    },
    location: {
      id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
      name: 'Colts',
      market: 'Indianapolis',
      alias: 'IND',
      sr_id: 'sr:competitor:4421',
      yardline: 40,
    },
  },
  last_event: {
    type: 'play',
    id: 'e83c3a80-ad0f-11ee-b18e-11f7316c1a9e',
    sequence: 1704599459837,
    clock: '9:43',
    home_points: 17,
    away_points: 17,
    play_type: 'pass',
    wall_clock: '2024-01-07T03:50:41+00:00',
    description:
      'C.Stroud pass short right complete to IND 40. Catch made by N.Collins at IND 40. Gain of 14 yards. N.Collins ran out of bounds.',
    fake_punt: false,
    fake_field_goal: false,
    screen_pass: false,
    play_action: false,
    run_pass_option: false,
    created_at: '2024-01-07T03:50:59+00:00',
    updated_at: '2024-01-07T03:51:46+00:00',
    start_situation: {
      clock: '9:43',
      down: 2,
      yfd: 14,
      possession: {
        id: '82d2d380-3834-4938-835f-aec541e5ece7',
        name: 'Texans',
        market: 'Houston',
        alias: 'HOU',
        sr_id: 'sr:competitor:4324',
      },
      location: {
        id: '82d2d380-3834-4938-835f-aec541e5ece7',
        name: 'Texans',
        market: 'Houston',
        alias: 'HOU',
        sr_id: 'sr:competitor:4324',
        yardline: 46,
      },
    },
    end_situation: {
      clock: '9:43',
      down: 1,
      yfd: 10,
      possession: {
        id: '82d2d380-3834-4938-835f-aec541e5ece7',
        name: 'Texans',
        market: 'Houston',
        alias: 'HOU',
        sr_id: 'sr:competitor:4324',
      },
      location: {
        id: '82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9',
        name: 'Colts',
        market: 'Indianapolis',
        alias: 'IND',
        sr_id: 'sr:competitor:4421',
        yardline: 40,
      },
    },
    statistics: [
      {
        stat_type: 'pass',
        attempt: 1,
        complete: 1,
        yards: 14,
        att_yards: 14,
        firstdown: 1,
        inside_20: 0,
        goaltogo: 0,
        blitz: 0,
        hurry: 0,
        knockdown: 0,
        on_target_throw: 0,
        batted_pass: 0,
        player: {
          id: '7e91086f-9ca4-4bd9-a099-b88b2f37e6c6',
          name: 'C.J. Stroud',
          jersey: '07',
          position: 'QB',
          sr_id: 'sr:player:2001139',
        },
        team: {
          id: '82d2d380-3834-4938-835f-aec541e5ece7',
          name: 'Texans',
          market: 'Houston',
          alias: 'HOU',
          sr_id: 'sr:competitor:4324',
        },
      },
      {
        stat_type: 'receive',
        firstdown: 1,
        target: 1,
        reception: 1,
        yards: 14,
        yards_after_catch: 0,
        inside_20: 0,
        goaltogo: 0,
        catchable: 0,
        player: {
          id: 'bd56a50c-5fae-4ee2-8363-f74ae07b6887',
          name: 'Nico Collins',
          jersey: '12',
          position: 'WR',
          sr_id: 'sr:player:2197774',
        },
        team: {
          id: '82d2d380-3834-4938-835f-aec541e5ece7',
          name: 'Texans',
          market: 'Houston',
          alias: 'HOU',
          sr_id: 'sr:competitor:4324',
        },
      },
      {
        stat_type: 'first_down',
        category: 'pass',
        team: {
          id: '82d2d380-3834-4938-835f-aec541e5ece7',
          name: 'Texans',
          market: 'Houston',
          alias: 'HOU',
          sr_id: 'sr:competitor:4324',
        },
      },
    ],
    details: [
      {
        category: 'pass_completion',
        description: 'C.Stroud pass short right complete to IND 40.',
        sequence: 0,
        direction: 'short right',
        yards: 14,
        start_location: {
          alias: 'HOU',
          yardline: 46,
        },
        end_location: {
          alias: 'IND',
          yardline: 40,
        },
        players: [
          {
            id: '7e91086f-9ca4-4bd9-a099-b88b2f37e6c6',
            name: 'C.J. Stroud',
            jersey: '07',
            position: 'QB',
            sr_id: 'sr:player:2001139',
            role: 'pass',
          },
        ],
      },
      {
        category: 'pass_reception',
        description: 'Catch made by N.Collins at IND 40. Gain of 14 yards.',
        sequence: 1,
        yards: 14,
        result: 'ran out of bounds',
        start_location: {
          alias: 'IND',
          yardline: 40,
        },
        end_location: {
          alias: 'IND',
          yardline: 40,
        },
        players: [
          {
            id: 'bd56a50c-5fae-4ee2-8363-f74ae07b6887',
            name: 'Nico Collins',
            jersey: '12',
            position: 'WR',
            sr_id: 'sr:player:2197774',
            role: 'catch',
          },
        ],
      },
      {
        category: 'ran_out_of_bounds',
        description: 'N.Collins ran out of bounds.',
        sequence: 2,
        start_location: {
          alias: 'IND',
          yardline: 40,
        },
        end_location: {
          alias: 'IND',
          yardline: 40,
        },
        players: [
          {
            id: 'bd56a50c-5fae-4ee2-8363-f74ae07b6887',
            name: 'Nico Collins',
            jersey: '12',
            position: 'WR',
            sr_id: 'sr:player:2197774',
            role: 'out_of_bounds',
          },
        ],
      },
      {
        category: 'first_down',
        sequence: 3,
        result: 'pass',
        start_location: {
          alias: 'IND',
          yardline: 40,
        },
        end_location: {
          alias: 'IND',
          yardline: 40,
        },
        players: [],
      },
    ],
  },
  scoring: [
    {
      period_type: 'quarter',
      id: '3783d9e7-4fb1-44ed-823b-d98f3f1642d3',
      number: 1,
      sequence: 1,
      home_points: 3,
      away_points: 7,
    },
    {
      period_type: 'quarter',
      id: '2b6d464b-9d52-409f-a8b3-d10f4c81fc33',
      number: 2,
      sequence: 2,
      home_points: 3,
      away_points: 7,
    },
    {
      period_type: 'quarter',
      id: '31b467ed-0f08-4499-9f26-bab75a930809',
      number: 3,
      sequence: 3,
      home_points: 8,
      away_points: 3,
    },
    {
      period_type: 'quarter',
      id: '3edcce8e-baa0-4fc5-8900-061bedcb5ee4',
      number: 4,
      sequence: 4,
      home_points: 3,
      away_points: 0,
    },
  ],
};
