export const demoGSNflGame01: unknown = {
  firstHalf: {
    drives: [],
    timeouts: [],
    timeoutsRemaining: {
      away: null,
      home: null,
    },
    coinToss: null,
  },
  secondHalf: {
    drives: [],
    timeouts: [],
    timeoutsRemaining: {
      away: null,
      home: null,
    },
    coinToss: null,
  },
  overtimePeriods: [],
  challenges: [],
  gameTime: {
    clock: '00:00:00',
    lastUpdatedUtc: '0001-01-01T00:00:00Z',
    isRunning: false,
  },
  playClock: {
    clock: '00:00:00',
    lastUpdatedUtc: '0001-01-01T00:00:00Z',
    isRunning: false,
  },
  matchStatus: 'NotStarted',
  period: null,
  periodWithStatus: null,
  score: {
    home: 0,
    away: 0,
    isConfirmed: true,
  },
  homeTeam: {
    offensive: [],
    defensive: [],
    special: [],
  },
  awayTeam: {
    offensive: [],
    defensive: [],
    special: [],
  },
  injuries: [],
  comments: [],
  currentPossession: {
    team: 'None',
    lastUpdatedUtc: '0001-01-01T00:00:00Z',
  },
  yardsToEndzone: {
    yards: null,
    team: 'None',
    lastUpdatedUtc: null,
    isConfirmed: null,
  },
  risks: {
    touchdown: 'Unknown',
    onsideKick: 'Unknown',
    fieldGoal: 'Unknown',
    fourthDown: 'Unknown',
    safety: 'Unknown',
    challenge: 'Unknown',
    penalty: 'Unknown',
    videoReview: 'Unknown',
    turnover: 'Unknown',
    other: 'Unknown',
    playAboutToStart: 'Unknown',
    injury: 'Unknown',
    bigPlay: 'Unknown',
    statDelay: 'Unknown',
  },
  isPlayUnderReview: null,
  nextPlay: null,
  source: 'GeniusPremium',
  fixtureId: 'demo-gs-nfl-01',
  sequence: 7,
  messageTimestampUtc: '2024-08-27T19:16:13.6682409Z',
  isReliable: false,
  isCoverageCancelled: false,
  reliabilityReasons: {
    heartbeat: 'Heartbeat Unknown',
    feedReliability: 'Feed Reliable',
    coverage: 'Coverage Available',
  },
};
