export const triviaData = [
  'The Sun is 99.86% of the mass of the entire Solar System',
  'The first computer virus was created in 1983?',
  'The first-ever text message was sent in 1992?',
  'The first-ever website is still online?',
  'Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.',
  "A single strand of spaghetti is called a 'spaghetto'.",
  'Octopuses have three hearts and blue blood.',
  'The Great Wall of China is not visible from space with the naked eye.',
  'Polar bears have black skin under their white fur.',
  "Bananas are berries, but strawberries aren't.",
  'The average person walks the equivalent of three times around the world in a lifetime.',
  'Cows have best friends and can become stressed when they are separated.',
  'The national animal of Scotland is the unicorn.',
  'Cleopatra VII of Egypt lived closer in time to the moon landing than to the construction of the Great Pyramid of Giza.',
  "A group of flamingos is called a 'flamboyance'.",
  'Penguins can jump as high as 6 feet in the air.',
  "The word 'gymnophobia' means the fear of nudity.",
  "The Earth's atmosphere weighs about 5.5 quadrillion tons.",
  "In Japan, it's considered good luck if a sumo wrestler makes your baby cry.",
  'The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.',
  'Cats have five toes on their front paws but only four on their back paws.',
  'The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.',
  'Turtles can breathe through their butts.',
  "The 'pound' key on your keyboard (#) is called an octothorpe.",
  "An ostrich's eye is bigger than its brain.",
  'Honeybees can recognize human faces.',
  "The world's oldest piece of chewing gum is over 9,000 years old.",
  'A day on Venus is longer than a year on Venus.',
  'The strongest muscle in the human body is the masseter (jaw muscle).',
  'Ants stretch when they wake up in the morning.',
  'Sea otters hold hands when they sleep to keep from drifting apart.',
  'The original purpose of bubble wrap was to be used as textured wallpaper.',
  'The average person spends six months of their lifetime waiting for red lights to turn green.',
  "A group of cats is called a 'clowder'.",
  "A flock of crows is known as a 'murder'.",
  'Apples float in water because they are 25% air.',
  "A 'jiffy' is an actual unit of time for 1/100th of a second.",
  'The average person sheds about 600,000 particles of skin every hour.',
  'Koalas sleep for up to 22 hours a day.',
  'The surface area of Russia is larger than the surface area of Pluto.',
  'Bees can recognize human faces.',
  'The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.',
  'Slugs have four noses.',
  'An octopus has three hearts.',
  "A 'jiffy' is an actual unit of time for 1/100th of a second.",
  'The moon has moonquakes.',
  "Kangaroos can't walk backward.",
  'A snail can sleep for three years.',
  'The first oranges weren’t orange.',
  'Humans are 70% water.',
  'Blue whales eat half a million calories in one mouthful.',
  'The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.',
  'An octopus has three hearts.',
  "A 'jiffy' is an actual unit of time for 1/100th of a second.",
  'The moon has moonquakes.',
  "Kangaroos can't walk backward.",
  'A snail can sleep for three years.',
  'Humans are 70% water.',
  'Blue whales eat half a million calories in one mouthful.',
];
