export const discussionPrompts = [
  "What's your favorite comfort food?",
  "What's your favorite childhood memory?",
  "What's your favorite smell?",
  "What's your favorite book?",
  "What's your favorite movie quote?",
  "What's your favorite way to relax?",
  "What's your favorite type of weather?",
  "What's your favorite type of cookie?",
  "What's your favorite type of music?",
  "What's your favorite TV show?",
  "What's your favorite dessert?",
  "What's your favorite hobby?",
  "What's your favorite holiday?",
  "What's your favorite season?",
  "What's your favorite place to visit?",
  "What's your favorite type of animal?",
  "What's your favorite flavor of ice cream?",
  "What's your favorite board game?",
  "What's your favorite type of tea or coffee?",
  "What's your favorite way to spend a rainy day?",
  "What's your favorite thing to do with friends?",
  "What's your favorite way to start the day?",
  "What's your favorite fruit?",
  "What's your favorite type of flower?",
  "What's your favorite type of candy?",
  "What's your favorite type of pizza?",
  "What's your favorite type of pasta?",
  "What's your favorite childhood cartoon?",
  "What's your favorite type of sandwich?",
  "What's your favorite outdoor activity?",
  'If you could have any superpower, but it only worked when you were doing the chicken dance, what would it be?',
  "What's the weirdest thing you've ever eaten, and did you like it?",
  'If you could live in any fictional universe for a day, where would you go and what would you do?',
  'If animals could talk, which one do you think would be the rudest?',
  'Would you rather fight one horse-sized duck or 100 duck-sized horses?',
  'If you could switch lives with any object for a day, what would it be?',
  "What's your favorite smell, and why?",
  'If you could only eat one food for the rest of your life, what would it be?',
  'If you could have a personal theme song that played every time you walked into a room, what would it be?',
  'If you could turn into any household item, which one would you choose?',
  'Would you rather have fingers for toes or toes for fingers?',
  'If you could have any celebrity be your imaginary friend, who would it be?',
  "What's the most useless talent you have?",
  'If you could only communicate using emojis for a day, how would you get your point across?',
  'If you could be any mythical creature, which one would you be?',
  "What's the most embarrassing thing you've ever worn in public?",
  'If you could only watch one movie for the rest of your life, what would it be?',
  'If you could only eat one color of food for a week, which color would you choose?',
  'If you could live in any video game world, which one would it be?',
  'If you could only speak in song lyrics for a day, what would you sing?',
  'If you could swap lives with any animal for a day, which one would you choose?',
  "What's the weirdest dream you've ever had?",
  'If you could have any animal as a pet, mythical or not, what would it be?',
  'If you could only listen to one song for the rest of your life, what would it be?',
  'If you could time travel to any decade, past or future, which one would you choose?',
  'If you could trade lives with any fictional character for a day, who would it be?',
  'If you could create a new holiday, what would it celebrate and how would people celebrate it?',
  'If you could have dinner with any historical figure, who would it be and what would you talk about?',
  'If you could be any flavor of ice cream, which one would you be?',
  'If you could only have one type of pizza topping for the rest of your life, what would it be?',
  'If you could only wear one color for the rest of your life, which color would you choose?',
  'Would you rather have the ability to fly or be invisible?',
  'Would you rather have the power to talk to animals or speak all foreign languages?',
  'Would you rather always be 10 minutes late or always be 20 minutes early?',
  'Would you rather have unlimited sushi for life or unlimited tacos for life?',
  'Would you rather be able to control fire or water?',
  'Would you rather have a rewind button for your life or a pause button?',
  'Would you rather have the ability to teleport anywhere or be able to read minds?',
  'Would you rather have the ability to time travel to the past or the future?',
  'Would you rather be able to speak with every living creature or speak and understand every language?',
  'Would you rather have the ability to never need sleep or never need to eat?',
  'Would you rather have fingers for toes or toes for fingers?',
  'Would you rather have the ability to change the past or see into the future?',
  'Would you rather have the ability to control the elements or control time?',
  'Would you rather live in a world without internet or a world without music?',
  'Would you rather have the ability to breathe underwater or fly through the air?',
  'Would you rather have the power to control your dreams or never have to sleep?',
  'Would you rather live in a house shaped like a circle or a house shaped like a triangle?',
  'Would you rather have the ability to be able to talk to plants or speak all human languages?',
  'Would you rather have unlimited money but no friends or have a lot of friends but live paycheck to paycheck?',
  'Would you rather always have to say everything on your mind or never speak again?',
  'Would you rather be able to control your dreams or control the dreams of others?',
  'Would you rather have the ability to fly but only at walking speed or run as fast as a car?',
  'Would you rather have the ability to stop time whenever you want or skip forward in time?',
  "Would you rather be a wizard in Harry Potter's world or a Jedi in Star Wars?",
  'Would you rather have the ability to never feel pain or never feel sadness?',
  'Would you rather be famous but unhappy or unknown but happy?',
  'Would you rather have the ability to become invisible at will or teleport anywhere?',
  'Would you rather have the ability to speak with animals or speak all foreign languages?',
  'Would you rather have a rewind button for your life or a pause button?',
  'Would you rather be able to time travel to the past or the future?',
  'Would you rather have the ability to never need sleep or never need to eat?',
  'Would you rather be able to breathe underwater or fly through the air?',
  'Would you rather have the ability to control fire or water?',
  'Would you rather always have to say everything on your mind or never speak again?',
  'Would you rather be able to control your dreams or control the dreams of others?',
  'Would you rather have the ability to stop time whenever you want or skip forward in time?',
  'Would you rather have the ability to control the weather or the traffic?',
  'Would you rather be able to talk to animals or speak and understand every language?',
  'Would you rather be able to control fire or ice?',
  'Would you rather be able to control minds or time?',
  'Would you rather live without music or without movies?',
  "Would you rather be a wizard in Harry Potter's world or a superhero in the Marvel Universe?",
  'Would you rather be able to talk to land animals, animals that fly, or animals that live underwater?',
  'Would you rather live without the internet or without AC and heating?',
  'Would you rather be an amazing painter or a brilliant mathematician?',
  'Would you rather always be 10 minutes late or 20 minutes early?',
  'Would you rather lose all of your money and valuables or all of the pictures you have ever taken?',
  'Would you rather be able to see 10 minutes into your own future or 10 minutes into the future of anyone but yourself?',
  'Would you rather have a horrible job, but be able to retire comfortably in 10 years or have your dream job, but have to work until the day you die?',
  'Would you rather find your true love or a suitcase with five million dollars inside?',
  'Would you rather be able to teleport anywhere or be able to read minds?',
  'Would you rather be able to control fire or ice?',
  'Would you rather have the ability to fly or be invisible?',
  'Would you rather have the ability to read minds or the ability to see into the future?',
  'Would you rather lose the ability to read or lose the ability to speak?',
  'Would you rather live in the desert or in the Arctic?',
  'Would you rather have a photographic memory or be able to forget anything you wanted?',
  'Would you rather have the ability to teleport anywhere or the ability to time travel?',
  'Would you rather have the ability to see 10 minutes into the future or 150 years into the future?',
  'Would you rather never be able to eat meat or never be able to eat vegetables?',
  'Would you rather never have to clean a bathroom again or never have to do dishes again?',
  'Would you rather be famous when you are alive and forgotten when you die or unknown when you are alive but famous after you die?',
  'Would you rather have all traffic lights you approach be green or never have to stand in line again?',
  'Would you rather have an unlimited gift certificate to a restaurant or a clothing store?',
  'Would you rather give up bathing for a month or give up the internet for a month?',
  'Would you rather be able to talk to land animals, animals that fly, or animals that live underwater?',
  'Would you rather be able to control the weather or the traffic?',
  'Would you rather be an amazing painter or a brilliant mathematician?',
  'Would you rather have the ability to see 10 minutes into your own future or 10 minutes into the future of anyone but yourself?',
  'Would you rather be famous for inventing a deadly new weapon or invent something that helps the world but someone else gets all the credit for inventing it?',
  'Would you rather be able to teleport anywhere or be able to read minds?',
  'Would you rather have unlimited sushi for life or unlimited tacos for life?',
  'Would you rather have your thoughts broadcasted so that everyone will always know what you are thinking while you are thinking it or never be allowed to wear clothes but keep your thoughts to yourself?',
  'Would you rather never have to pay for food at a restaurant or never have to pay for drinks at a bar?',
  'Would you rather be able to talk to animals or speak all foreign languages?',
  'Would you rather have the ability to teleport anywhere or the ability to time travel?',
  'Would you rather know when you are going to die or how you are going to die?',
  'Would you rather be an amazing artist but not be able to see any of the beauty you create or be an amazing musician and be deaf?',
  'Would you rather be famous but ridiculed or be just a normal person?',
  'Would you rather be able to hear any conversation or take back anything you say?',
  'Would you rather have your own private island or have your own private jet?',
  'Would you rather be able to run at 100 miles per hour or fly at 10 miles per hour?',
  'Would you rather know all the secrets of space or know all the secrets of the ocean?',
  'Would you rather have a rewind button for your life or a pause button?',
  'Would you rather have a dragon or be a dragon?',
  'Would you rather fight a hundred duck-sized horses or one horse-sized duck?',
  'Would you rather never have to sleep or never have to eat?',
  'Would you rather fight a zombie or a vampire?',
  'Would you rather have a bottomless bowl of guacamole or a bottomless bag of chips?',
  'Would you rather be stranded on a deserted island alone or with someone you hate?',
  'Would you rather have the ability to shrink to the size of an ant or grow to the size of a skyscraper?',
  'Would you rather be able to speak to animals or speak all foreign languages?',
  'Would you rather be able to run at 100 miles per hour or fly at 10 miles per hour?',
  'Would you rather have unlimited sushi for life or unlimited tacos for life?',
  'Would you rather never have to pay for food at a restaurant or never have to pay for drinks at a bar?',
  'Would you rather always be slightly late or super early?',
  'Would you rather be famous but ridiculed or just a normal person?',
  'Would you rather always have to say everything on your mind or never speak again?',
  'Would you rather be able to control fire or ice?',
  'Would you rather be able to control your dreams or be able to control time?',
  'Would you rather have to dance every time you heard music or sing along to every song you heard?',
  'Would you rather live in a tree house or in a cave?',
  'Would you rather never have to sleep or never have to eat?',
  "Would you rather always have a song stuck in your head or always have an itch you can't reach?",
  'Would you rather have a rewind button for your life or a pause button?',
  'Would you rather be able to talk to land animals, animals that fly, or animals that live underwater?',
  'Would you rather be able to see 10 minutes into your own future or 10 minutes into the future of anyone but yourself?',
  'Would you rather always have to say everything on your mind or never speak again?',
  'Would you rather have the ability to stop time whenever you want or skip forward in time?',
];
