import { describe, expect, it } from 'vitest';

import { stripXmlPreamble } from './icons.js';

describe('stripXmlPreamble', () => {
  it('strips <?xml?> declaration', () => {
    const input = '<?xml version="1.0" encoding="UTF-8"?>\n<svg viewBox="0 0 24 24"></svg>';
    expect(stripXmlPreamble(input)).toBe('<svg viewBox="0 0 24 24"></svg>');
  });

  it('strips <!DOCTYPE> declaration', () => {
    const input =
      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n<svg></svg>';
    expect(stripXmlPreamble(input)).toBe('<svg></svg>');
  });

  it('strips XML comments before <svg>', () => {
    const input = '<!-- generated by Inkscape -->\n<svg></svg>';
    expect(stripXmlPreamble(input)).toBe('<svg></svg>');
  });

  it('strips combined preamble (<?xml?> + <!DOCTYPE> + comment)', () => {
    const input = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">',
      '<!-- Created with Illustrator -->',
      '<svg viewBox="0 0 100 100"></svg>',
    ].join('\n');
    expect(stripXmlPreamble(input)).toBe('<svg viewBox="0 0 100 100"></svg>');
  });

  it('returns input unchanged when no preamble exists', () => {
    const input = '<svg viewBox="0 0 24 24"><path d="M0 0"/></svg>';
    expect(stripXmlPreamble(input)).toBe(input);
  });

  it('handles leading whitespace before <svg>', () => {
    const input = '  \n  <svg></svg>';
    expect(stripXmlPreamble(input)).toBe('<svg></svg>');
  });
});
