export const nflTeams: GSNFLTeamInfo[] = [
  {
    id: '111701',
    shortName: 'Cardinals',
    market: 'Arizona',
    fullName: 'Arizona Cardinals',
    abbreviation: 'ARI',
    logo: 'nfl-ari.png',
  },
  {
    id: '112016',
    shortName: 'Falcons',
    market: 'Atlanta',
    fullName: 'Atlanta Falcons',
    abbreviation: 'ATL',
    logo: 'nfl-atl.png',
  },
  {
    id: '93331',
    shortName: 'Ravens',
    market: 'Baltimore',
    fullName: 'Baltimore Ravens',
    abbreviation: 'BAL',
    logo: 'nfl-bal.png',
  },
  {
    id: '112554',
    shortName: 'Bills',
    market: 'Buffalo',
    fullName: 'Buffalo Bills',
    abbreviation: 'BUF',
    logo: 'nfl-buf.png',
  },
  {
    id: '113372',
    shortName: 'Panthers',
    market: 'Carolina',
    fullName: 'Carolina Panthers',
    abbreviation: 'CAR',
    logo: 'nfl-car.png',
  },
  {
    id: '102222',
    shortName: 'Bears',
    market: 'Chicago',
    fullName: 'Chicago Bears',
    abbreviation: 'CHI',
    logo: 'nfl-chi.png',
  },
  {
    id: '102450',
    shortName: 'Bengals',
    market: 'Cincinnati',
    fullName: 'Cincinnati Bengals',
    abbreviation: 'CIN',
    logo: 'nfl-cin.png',
  },
  {
    id: '102649',
    shortName: 'Browns',
    market: 'Cleveland',
    fullName: 'Cleveland Browns',
    abbreviation: 'CLE',
    logo: 'nfl-cle.png',
  },
  {
    id: '96760',
    shortName: 'Cowboys',
    market: 'Dallas',
    fullName: 'Dallas Cowboys',
    abbreviation: 'DAL',
    logo: 'nfl-dal.png',
  },
  {
    id: '82865',
    shortName: 'Broncos',
    market: 'Denver',
    fullName: 'Denver Broncos',
    abbreviation: 'DEN',
    logo: 'nfl-den.png',
  },
  {
    id: '82959',
    shortName: 'Lions',
    market: 'Detroit',
    fullName: 'Detroit Lions',
    abbreviation: 'DET',
    logo: 'nfl-det.png',
  },
  {
    id: '115649',
    shortName: 'Packers',
    market: 'Green Bay',
    fullName: 'Green Bay Packers',
    abbreviation: 'GB',
    logo: 'nfl-gb.png',
  },
  {
    id: '104405',
    shortName: 'Texans',
    market: 'Houston',
    fullName: 'Houston Texans',
    abbreviation: 'HOU',
    logo: 'nfl-hou.png',
  },
  {
    id: '105059',
    shortName: 'Colts',
    market: 'Indianapolis',
    fullName: 'Indianapolis Colts',
    abbreviation: 'IND',
    logo: 'nfl-ind.png',
  },
  {
    id: '84868',
    shortName: 'Jaguars',
    market: 'Jacksonville',
    fullName: 'Jacksonville Jaguars',
    abbreviation: 'JAX',
    logo: 'nfl-jax.png',
  },
  {
    id: '86068',
    shortName: 'Chiefs',
    market: 'Kansas City',
    fullName: 'Kansas City Chiefs',
    abbreviation: 'KC',
    logo: 'nfl-kc.png',
  },
  {
    id: '119948',
    shortName: 'Raiders',
    market: 'Las Vegas',
    fullName: 'Las Vegas Raiders',
    abbreviation: 'LV',
    logo: 'nfl-lv.png',
  },
  {
    id: '106518',
    shortName: 'Chargers',
    market: 'Los Angeles',
    fullName: 'Los Angeles Chargers',
    abbreviation: 'LAC',
    logo: 'nfl-lac.png',
  },
  {
    id: '107844',
    shortName: 'Rams',
    market: 'Los Angeles',
    fullName: 'Los Angeles Rams',
    abbreviation: 'LAR',
    logo: 'nfl-lar.png',
  },
  {
    id: '100604',
    shortName: 'Dolphins',
    market: 'Miami',
    fullName: 'Miami Dolphins',
    abbreviation: 'MIA',
    logo: 'nfl-mia.png',
  },
  {
    id: '86237',
    shortName: 'Vikings',
    market: 'Minnesota',
    fullName: 'Minnesota Vikings',
    abbreviation: 'MIN',
    logo: 'nfl-min.png',
  },
  {
    id: '119172',
    shortName: 'Patriots',
    market: 'New England',
    fullName: 'New England Patriots',
    abbreviation: 'NE',
    logo: 'nfl-ne.png',
  },
  {
    id: '119191',
    shortName: 'Saints',
    market: 'New Orleans',
    fullName: 'New Orleans Saints',
    abbreviation: 'NO',
    logo: 'nfl-no.png',
  },
  {
    id: '119884',
    shortName: 'Giants',
    market: 'New York',
    fullName: 'New York Giants',
    abbreviation: 'NYG',
    logo: 'nfl-nyg.png',
  },
  {
    id: '119885',
    shortName: 'Jets',
    market: 'New York',
    fullName: 'New York Jets',
    abbreviation: 'NYJ',
    logo: 'nfl-nyj.png',
  },
  {
    id: '89169',
    shortName: 'Eagles',
    market: 'Philadelphia',
    fullName: 'Philadelphia Eagles',
    abbreviation: 'PHI',
    logo: 'nfl-phi.png',
  },
  {
    id: '89402',
    shortName: 'Steelers',
    market: 'Pittsburgh',
    fullName: 'Pittsburgh Steelers',
    abbreviation: 'PIT',
    logo: 'nfl-pit.png',
  },
  {
    id: '106530',
    shortName: '49ers',
    market: 'San Francisco',
    fullName: 'San Francisco 49ers',
    abbreviation: 'SF',
    logo: 'nfl-sf.png',
  },
  {
    id: '90401',
    shortName: 'Seahawks',
    market: 'Seattle',
    fullName: 'Seattle Seahawks',
    abbreviation: 'SEA',
    logo: 'nfl-sea.png',
  },
  {
    id: '92305',
    shortName: 'Buccaneers',
    market: 'Tampa Bay',
    fullName: 'Tampa Bay Buccaneers',
    abbreviation: 'TB',
    logo: 'nfl-tb.png',
  },
  {
    id: '121182',
    shortName: 'Titans',
    market: 'Tennessee',
    fullName: 'Tennessee Titans',
    abbreviation: 'TEN',
    logo: 'nfl-ten.png',
  },
  {
    id: '109493',
    shortName: 'Commanders',
    market: 'Washington',
    fullName: 'Washington Commanders',
    abbreviation: 'WAS',
    logo: 'nfl-was.png',
  },
];

export type GSNFLTeamInfo = {
  id: string;
  shortName: string;
  market: string;
  fullName: string;
  abbreviation: string;
  logo: string;
};

export function teamInfoForId(id: string): GSNFLTeamInfo {
  const team = nflTeams.find((team) => String(team.id) === String(id));
  return team ?? { id: id, shortName: '', fullName: '', market: '', abbreviation: '', logo: '' };
}
